apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"

      - name: Checkout3
        uses: cloudbees-io/checkout@v1
        id: checkout3
        with:
          provider: github
          repository: insights-test-prod/prod-python-hello-world
          ref: e54c06389c050a7204ca68dbb052ba4f39a906a5
